const days = [
  {
    id: 1,
    day: "1",
    note: "",
  },
  { id: 2, day: "2", note: "" },
  { id: 3, day: "3", note: "" },
  { id: 4, day: "4", note: "" },
  { id: 5, day: "5", note: "" },
  { id: 6, day: "6", note: "" },
  { id: 7, day: "7", note: "" },
  { id: 8, day: "8", note: "" },
  { id: 9, day: "9", note: "" },
  { id: 10, day: "10", note: "" },
  { id: 11, day: "11", note: "" },
  { id: 12, day: "12", note: "" },
  { id: 13, day: "13", note: "" },
  { id: 14, day: "14", note: "" },
  { id: 15, day: "15", note: "" },
  { id: 16, day: "16", note: "" },
  { id: 17, day: "17", note: "" },
  { id: 18, day: "18", note: "" },
  { id: 19, day: "19", note: "" },
  { id: 20, day: "20", note: "" },
  { id: 21, day: "21", note: "" },
  { id: 22, day: "22", note: "" },
  { id: 23, day: "23", note: "" },
  { id: 24, day: "24", note: "" },
  { id: 25, day: "25", note: "" },
  { id: 26, day: "26", note: "" },
  { id: 27, day: "27", note: "" },
  { id: 28, day: "28", note: "" },
  { id: 29, day: "29", note: "" },
  { id: 30, day: "30", note: "" },
  { id: 31, day: "31", note: "" },
];

export default days;
